config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',    to: 'static_pages#about'
  get  '/contact',    to: 'static_pages#contact'
  get  '/signup', to: 'users#new'
  post  '/signup', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, except: [:new,]
  resources :posts
  resources :catagories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/catagory.rb
class Catagory < ApplicationRecord
  validates :name, presence: true,
                   uniqueness: true,
                   length: {minimum: 3, maximum:15}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum: 20, maximum:100}
  validates :body, presence: true, length: {minimum:30, maximum:1000}
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  before_save {self.email = email.downcase}
  validates :name, presence: true,
            uniqueness: {case_sensitive: false},
            length: {minimum: 3, maximum:20}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false},
                    length: {minimum: 10, maximum: 255}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in for this action"
      redirect_to root_path
    end
  end
end

app/controllers/catagories_controller.rb
class CatagoriesController < ApplicationController
  def new
  end
  def create
  end
  def index
  end
  def show
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only:[:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:success] = 'Post is successfully created'
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def update
    if @post.update(post_params)
      flash[:success] = 'Post is successfully updated'
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def show
  end

  def index
    @posts = Post.paginate(page: params[:page], per_page:5)
  end

  def destroy
    @post.destroy
    flash[:success] = 'Post is successfully deleted.'
    redirect_to posts_path
  end
  private
    def set_post
      @post = Post.find(params[:id])
    end
    def post_params
      params.require(:post).permit(:title, :body)
    end

    def require_same_user
      if (current_user != @post.user) && !current_user.admin?
        flash[:danger] = "You can only delete your own posts"
        redirect_to root_path
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Either your email or password is incorrect"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out successfully"
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    redirect_to posts_path if logged_in?
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update]
  before_action :require_admin, only: [:destroy]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to our site! #{@user.name}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update (user_params)
       flash[:success] = "Your account is updated successfully."
       redirect_to posts_path
    else
       render 'edit'
    end
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def show
      @user_posts = @user.posts.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "user and all the related posts are deleted"
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin can perform this action"
      redirect_to root_path
    end
  end
  def require_same_user
    if current_user!= @user and !current_user.admin?
      flash[:danger] = "You can update your own profile only"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = {size:80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt:user.name, class: "img-circle")
  end
end

app/helpers/catagories_helper.rb
module CatagoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer-section">
    <nav>
      <ul>
        <li id="about"><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "Help", help_path %></li>
      </ul>
    </nav>
    <small class="copyright-section">
      Copyright &copy; <a href="#">Blog Post</a> By <a href="#">Suman Shrestha</a>
    </small>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class= 'alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismis= 'alert'>&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">

<div class="container-fluid">

<!-- Brand and toggle get grouped for better mobile display -->

<div class="navbar-header">

<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">

<span class="sr-only">Toggle navigation</span>

<span class="icon-bar"></span>

<span class="icon-bar"></span>

<span class="icon-bar"></span>

</button>

<%= link_to "Blog Post", root_path, class: "navbar-brand", id: "logo" %>

</div>

<!-- Collect the nav links, forms, and other content for toggling -->

<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

<ul class="nav navbar-nav">

<li><%= link_to "Posts", posts_path %></li>

<li><%= link_to "Users", users_path %></li>

<% if logged_in? %>

<li class="dropdown">

<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>

<ul class="dropdown-menu">

<li><%= link_to "New Post", new_post_path %></li>

<li><a href="#">Another action</a></li>

<li><a href="#">Something else here</a></li>

<li role="separator" class="divider"></li>

<li><a href="#">Separated link</a></li>

<li role="separator" class="divider"></li>

<li><a href="#">One more separated link</a></li>

</ul>

</li>

<% end %>

</ul>

<form class="navbar-form navbar-left" role="search">

<div class="form-group">

<input type="text" class="form-control" placeholder="Search">

</div>

<button type="submit" class="btn btn-default">Submit</button>

</form>

<ul class="nav navbar-nav navbar-right">

<% if logged_in? %>

<li><%= link_to 'Log out', logout_path, method: :delete %></li>

<li class="dropdown">

<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%=current_user.name%><%="admin" if current_user.admin? %><span class="caret"></span></a>

<ul class="dropdown-menu">

<li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>

<li><%= link_to "View your profile", user_path(current_user) %></li>

<li><a href="#">Something else here</a></li>

<li role="separator" class="divider"></li>

<li><a href="#">Separated link</a></li>

</ul>

</li>

<% else %>

<li><%= link_to 'Log in', login_path %></li>

<li><%= link_to 'Sign up', signup_path %></li>

<% end %>

</ul>

</div><!-- /.navbar-collapse -->

</div><!-- /.container-fluid -->

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title>Blog Post</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/posts/_error_messages.html.erb
<% if @post.errors.any? %>
<div class="row">
  <div class="col-xs-8, col-xs-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
          <%= pluralize(@post.errors.count, "error") %>
           prohibited this article from being saved:
        </h2>
        <div class ="panel-body">
          <ul>
            <% @post.errors.full_messages.each do |message| %>
            <li><%= message %> </li>
            <% end %>
           </ul>
         </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @post do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Title of the post", autofocus: true %><br>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', placeholder: "Discription of the post"%><br>
      </div>
      <%= f.submit "Save", class: "btn btn-success btn-lg" %>
    <% end %>
    <div class="col-xs-4, col-xs-offset-4">
      <%= link_to "Cancel the post", posts_path %>
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<% obj.each do |post| %>
  <div class="row">
    <div class="col-xs-8, col-xs-offset-1">
      <div class="well well-lg">
        <div class="post-title">
          <%= link_to post.title, post_path(post)%>
        </div>
        <div class="post-body">
          <%= truncate(post.body, length:100) %> <!--will preserve the formatting in the description -->
          <div class="post-meta-details">
            <small>
              Created By: <%= post.user.name if post.user%>,
              <%= time_ago_in_words(post.created_at) %> ago,
             last updated: <%= time_ago_in_words(post.updated_at) %> ago
            </small>
          </div>
        </div>
        <br>
        <% if logged_in? && (current_user == post.user || current_user.admin?)%>
          <div class="post-actions">
            <%= link_to "View all posts", posts_path, class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete this post", post_path(post),method: :delete,
                                            data: {confirm: "Are you sure that you want to delete the post?"},
                                            class: "btn btn-xs btn-danger" %>
            <%= link_to "Edit this post", edit_post_path(post), class: "btn btn-xs btn-info" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'error_messages' %>
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="row">
  <div class="mb-1 col-md-12 col-xs-offset-1 ">
    <h1>List of all the articles</h1>
    <%= link_to "Create new post", new_post_path, class: "btn btn-xs btn-primary" %>
  </div>
</div>
<%= render 'post', obj: @posts %>
<div align = "center">
  <%= will_paginate %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'shared/error_messages', obj: @post %>
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="container">
  <h2 class="post-title", align= "center"><%= @post.title %></h2>
  <div class="well col-xs-8, col-xs-offset-1">
    <ul class="listing">
      <div class="row center">
        <div class="col-md-4 col-md-offset-4">
          <li> <%= link_to gravatar_for(@post.user), user_path(@post.user) %></li>
          <li class="post-title">
            <%= link_to @post.user.name, user_path(@post.user) %>
          </li>
          <li>
            <small>
              <%= pluralize(@post.user.posts.count, "post") if @post.user.posts %>
            </small>
          </li>
        </div>
      </div>
    </ul>
    <%= simple_format(@post.body) %> <!--will preserve the formatting in the description -->
    <br>
    <div class="post-actions">
      <% if logged_in? && (current_user == @post.user || current_user.admin?)%>
        <%= link_to "Edit this post", edit_post_path(@post), class: "btn btn-xs btn-info" %>
        <%= link_to "Delete this post", post_path(@post),method: :delete,
                                        data: {confirm: "Are you sure that you want to delete the post?"},
                                        class: "btn btn-xs btn-danger" %>
      <% end %>
      <%= link_to "View all posts", posts_path, class: "btn btn-xs btn-primary" %>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if obj.errors.any? %>
<div class="row">
  <div class="col-xs-8, col-xs-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
          <%= pluralize(obj.errors.count, "error") %>
           prohibited this article from being saved:
        </h2>
        <div class ="panel-body">
          <ul>
            <% obj.errors.full_messages.each do |message| %>
            <li><%= message %> </li>
            <% end %>
           </ul>
         </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>Details of the company</h1>

app/views/static_pages/contact.html.erb
<h1>This is a contact page and feel free to contact us </h1>

app/views/static_pages/help.html.erb
<h1>This is a help page and Please follow the following instruction to reach to us </h1>

app/views/static_pages/home.html.erb
<div class="center jumbotron text-center">
    <h1>Welcome to the Blogpost App</h1>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/_form.html.erb
<%= render 'shared/error_messages', obj: @user %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:user, url:users_path) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', placeholder: "Enter your name"%>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control', placeholder: "Enter your email"%>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control', placeholder: "Enter your password"%>

      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'update') %>
<% provide(:button_text, 'Update my account') %>

<h1 align ="center">Edit your account </h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 align= "center"> All the Authors </h1>
<div align = "center">
  <% @users.each do |user| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li> <%= link_to gravatar_for(user), user_path(user) %></li>
          <li class="article-title">
            <%= link_to user.name, user_path(user) %>
          </li>
          <li>
            <small>
              <%= pluralize(user.posts.count, "post") if user.posts %>
            </small>
          </li>
          <% if logged_in? and current_user.admin? %>
            <li><%= link_to "Delete this user", user_path(user), method: :delete,
                  data: {confirm: "Are you sure you want to delete this user and articles?"}, class: "btn btn-sm btn-danger"%>
            </li>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
</div>
<div align = "center">
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create account') %>
<h1 class="text-center">Sign up</h1>
<%=render 'form' %>

app/views/users/show.html.erb
<h1 align= "center">Welcome to <%= @user.name %>'s homepage </h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user, size:150 %>
  </div>
</div>
<h4 align="center"><%= @user.name%>'s posts</h4>
<%= render 'posts/post', obj: @user_posts %>
<div class="center">
  <%= will_paginate @user_posts %>
</div>